dependencies:
  - keras==2.12.0
  - Keras_Preprocessing==1.1.2
  - matplotlib==3.7.2
  - nltk==3.8.1
  - numpy==1.23.5
  - pandas==2.0.3
  - scikit_learn==1.3.0
  - tensorflow==2.12.0
  - tqdm==4.65.0
  - watermark==2.4.3
